### ISSUE TITLE
Login access

### ISSUE THREAD

**Issue by Koploseus** [driemworks/iris-deprecated#19]
What is the login for testing ? 

How to "sign in" also ?

**Comment by driemworks** [comment]
Currently, there is no dedicated login account for testing, so you will have to create your own. I'll need to update the readme to provide more details, however, to "sign in" you must:

1) have a local IPFS node running
2) (optional, if you want to create a new username/password for your machine) clear your browser's localstorage for localhost
3) enter any username/password combo you want

What this does is:
1) generates a mnemonic phrase, which is encrypted with the browser-passworder library and then stored in your browser's localstorage (hence the optional step 2 above for new username/password combo. This is useful when you'd like to generate multiple accounts for testing, particularly the share functionality.)
2) uses your username/password to create a new ethereum account. 

On login, when the password is accepted, the password is used to decrypt the mnemonic phrase. Then the password, in conjunction with the mnemonic phrase, is used to recover the ethereum account. 

Note: The reason for using ethereum is for future features that will be implemented, where user's can interact with smart contracts.

**Comment by Koploseus** [comment]
Thanks for the answer!
I don't have any account yet.. and it keep telling me to put my alias and password (even if i clear my browser's storage) i can't even create one

**Comment by driemworks** [comment]
Do you see any errors in the console logs or in the outgoing http calls?

**Comment by Koploseus** [comment]
Those are the errors 
![image](https://user-images.githubusercontent.com/25018500/82639320-c7900f80-9c08-11ea-8875-db0d63363cf5.png)

**Comment by driemworks** [comment]
That all looks as expected, just unused import warnings that need to be cleaned up. Can you check if there are network issues? I have a feeling there could be an error when attempting to call IPFS, in which case it may be the local ipfs config that is the root cause.
